In [ ]:
import pandas as pd
import streamlit as st
import plotly.express as px

In [ ]:
vendas_df = pd.read_excel("faturamento_multinacional.xlsx")
display(vendas_df)
print(vendas_df.columns)
print(vendas_df.dtypes)

In [ ]:
# Lista das colunas financeiras
colunas_moedas = [
    "Preço Unitário (R$)", "Receita Bruta (R$)", "Custo do Produto (R$)", 
    "Margem de Lucro (R$)", "Descontos Aplicados (R$)", "Impostos (R$)", "Receita Líquida (R$)"
]


# Remover espaços extras nos nomes das colunas
vendas_df.columns = vendas_df.columns.str.strip()

# Filtrar apenas colunas que existem no DataFrame
colunas_existentes = [col for col in colunas_moedas if col in vendas_df.columns]



# Exibir o DataFrame com os valores formatados
display(vendas_df)
print(vendas_df.dtypes)

In [ ]:
# Verifica se as colunas necessárias existem no DataFrame vendas_df.
# Se alguma coluna não existir, exibe uma mensagem de erro.
colunas_necessarias = ["Receita Líquida (R$)", "Custo do Produto (R$)", "Impostos (R$)", "País"]
for col in colunas_necessarias:
    if col not in vendas_df.columns:
        print(f"Erro: A coluna '{col}' não existe no DataFrame.")

# Exibe os tipos de dados das colunas "Receita Líquida (R$)", "Custo do Produto (R$)" e "Impostos (R$)".
# Isso ajuda a garantir que as colunas sejam numéricas e possam ser usadas em cálculos.
print("Tipos de dados das colunas:")
print(vendas_df[["Receita Líquida (R$)", "Custo do Produto (R$)", "Impostos (R$)"]].dtypes)

# Cria uma nova coluna no DataFrame vendas_df chamada "Lucro País(R$)".
# Essa coluna é calculada subtraindo o "Custo do Produto (R$)" e o "Impostos (R$)" da "Receita Líquida (R$)".
vendas_df["Lucro País(R$)"] = vendas_df["Receita Líquida (R$)"] - vendas_df["Custo do Produto (R$)"] - vendas_df["Impostos (R$)"]

# Agrupa o DataFrame vendas_df pela coluna "País".
# Para cada grupo (país), soma os valores das colunas "Receita Líquida (R$)" e "Lucro País(R$)".
# O resultado é armazenado em um novo DataFrame chamado df_agrupado.
df_agrupado = vendas_df.groupby('País').agg({
    "Receita Líquida (R$)": "sum",  # Soma a "Receita Líquida (R$)" para cada país.
    "Lucro País(R$)": "sum"         # Soma o "Lucro País(R$)" para cada país.
}).reset_index()  # Reseta o índice do DataFrame agrupado, transformando a coluna "País" em uma coluna normal.

# Exibe o DataFrame df_agrupado, que contém a soma da receita líquida e do lucro por país.
print(df_agrupado)

In [24]:


# Supondo que você já tem o DataFrame vendas_df carregado
# Agrupa o DataFrame pela coluna "País" e soma a "Quantidade Vendida"
df_quantidade_vendas_por_pais = vendas_df.groupby("País").agg({
    "Quantidade Vendida": "sum"
}).reset_index()

# Renomeia a coluna "Quantidade Vendida" para "Total Quantidade Vendida"
df_quantidade_vendas_por_pais = df_quantidade_vendas_por_pais.rename(columns={
    "Quantidade Vendida": "Total Quantidade Vendida"
})

# Exibe o DataFrame resultante
print(df_quantidade_vendas_por_pais)

          País  Total Quantidade Vendida
0     Alemanha                   1270794
1    Austrália                   1291442
2       Brasil                   1254152
3       Canadá                   1252616
4        China                   1291718
5          EUA                   1276490
6       França                   1255175
7        Japão                   1247338
8  Reino Unido                   1259743
9        Índia                   1317213

In [25]:
# Verifica se as colunas necessárias existem no DataFrame vendas_df.
# Se alguma coluna não existir, exibe uma mensagem de erro.
colunas_necessarias = ["País", "Produto", "Quantidade Vendida"]
for col in colunas_necessarias:
    if col not in vendas_df.columns:
        print(f"Erro: A coluna '{col}' não existe no DataFrame.")

# Agrupa o DataFrame vendas_df pelas colunas "País" e "Produto".
# Para cada grupo (país e produto), soma os valores da coluna "Quantidade Vendida".
df_quantidade_produtos_por_pais = vendas_df.groupby(['País', 'Produto']).agg({
    "Quantidade Vendida": "sum"  # Soma a quantidade vendida por país e produto.
}).reset_index()  # Reseta o índice do DataFrame agrupado, transformando "País" e "Produto" em colunas normais.

# Renomeia a coluna "Quantidade Vendida" para "Total Quantidade Vendida".
df_quantidade_produtos_por_pais = df_quantidade_produtos_por_pais.rename(columns={
    "Quantidade Vendida": "Total Quantidade Vendida"
})

# Exibe o DataFrame df_quantidade_produtos_por_pais.
print(df_quantidade_produtos_por_pais)
display(vendas_df)

         País            Produto  Total Quantidade Vendida
0    Alemanha              Arroz                     41796
1    Alemanha            Bateria                     41727
2    Alemanha              Batom                     42730
3    Alemanha           Biscoito                     42875
4    Alemanha            Cadeira                     42003
..        ...                ...                       ...
295     Índia             Tablet                     39836
296     Índia              Tênis                     43866
297     Índia   Velas de Ignição                     41878
298     Índia            Vestido                     33680
299     Índia  Óleo Lubrificante                     47728

[300 rows x 3 columns]

,Ano,Mês,País,Região,Categoria,Produto,Quantidade Vendida,Preço Unitário (R$),Receita Bruta (R$),Custo do Produto (R$),Margem de Lucro (R$),Descontos Aplicados (R$),Impostos (R$),Receita Líquida (R$),Lucro País(R$)
0,2021,11,França,Oceania,Automotivo,Óleo Lubrificante,476,508.87,242222.12,1.302609e+05,111961.199934,8083.160725,16724.551173,2.174144e+05,70428.936862
1,2020,6,Índia,América do Sul,Móveis,Mesa,201,4961.14,997189.14,5.835994e+05,413589.727335,60993.388909,47802.104293,8.883936e+05,256992.129840
2,2018,1,Austrália,Ásia,Móveis,Cadeira,373,2576.03,960859.19,5.551118e+05,405747.419166,4463.230594,134977.814198,8.214181e+05,131328.560176
3,2022,9,Canadá,América do Sul,Móveis,Sofá,325,2820.81,916763.25,4.727060e+05,444057.244358,1463.727328,77465.527391,8.378340e+05,287662.462250
4,2021,12,Canadá,Ásia,Automotivo,Filtro de Ar,215,1961.39,421698.85,1.917342e+05,229964.685405,31853.503807,44354.023171,3.454913e+05,109403.135256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2018,5,França,Oceania,Eletrônicos,Smartphone,461,4278.66,1972462.26,9.742057e+05,998256.510366,97459.188568,215888.219038,1.659115e+06,469020.883720
49996,2019,10,Brasil,América do Norte,Roupas,Camiseta,337,1201.61,404942.57,2.613432e+05,143599.328306,33235.269838,43148.038017,3.285593e+05,24067.982434
49997,2018,11,Índia,Ásia,Roupas,Calça Jeans,173,4024.16,696179.68,3.927182e+05,303461.460932,44336.671657,112971.752856,5.388713e+05,33181.283562
49998,2022,1,China,Ásia,Roupas,Calça Jeans,436,3722.63,1623066.68,1.011501e+06,611565.469845,130246.268759,153657.061749,1.339163e+06,174005.077589
49999,2019,7,Austrália,Oceania,Roupas,Calça Jeans,279,1972.93,550447.47,3.548139e+05,195633.614890,7022.268694,41220.265535,5.022049e+05,106170.815126

2025-02-21 18:07:55.019 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:55.208
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-02-21 18:07:55.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:55.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:55.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-21 18:07:56.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()